In [3]:
import numpy as np
import math

In [4]:
print("Sreenivas")

Sreenivas


In [5]:
a =  np.array([[1,2,3],[4,5,6]]) 
# a.shape output:(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [61]:
a = np.array([1,2,3,4,5,6,7])
a.size


7

In [7]:
a[2]

np.int64(3)

In [8]:
a[:4]

array([1, 2, 3, 4])

In [9]:
a[4:]

array([5, 6, 7])

In [65]:
a =  np.array([[1,2,3],[4,5,6]])
a.shape

(2, 3)

In [11]:
"""You might hear of a 0-D (zero-dimensional) array referred to as a “scalar”, a 1-D (one-dimensional) array as a
“vector”, a 2-D (two-dimensional) array as a “matrix”, or an N-D (N-dimensional, where “N” is typically an integer 
greater than 2) array as a “tensor”. For clarity, it is best to avoid the mathematical terms when referring to an array
because the mathematical objects with these names behave differently than arrays (e.g. “matrix” multiplication is
fundamentally different from “array” multiplication), and there are other objects in the scientific Python ecosystem
that have these names (e.g. the fundamental data structure of PyTorch is the “tensor”)."""

'You might hear of a 0-D (zero-dimensional) array referred to as a “scalar”, a 1-D (one-dimensional) array as a\n“vector”, a 2-D (two-dimensional) array as a “matrix”, or an N-D (N-dimensional, where “N” is typically an integer \ngreater than 2) array as a “tensor”. For clarity, it is best to avoid the mathematical terms when referring to an array\nbecause the mathematical objects with these names behave differently than arrays (e.g. “matrix” multiplication is\nfundamentally different from “array” multiplication), and there are other objects in the scientific Python ecosystem\nthat have these names (e.g. the fundamental data structure of PyTorch is the “tensor”).'

In [12]:
a.shape
len(a.shape) == a.ndim

True

In [13]:
a.size

6

In [14]:
a.size == math.prod(a.shape)

True

In [15]:
a.dtype

dtype('int64')

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
""" The function empty creates an array whose initial content is random and depends on the state of the memory. 
The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!"""
np.empty(2) 

array([-2.00221313e-289,  4.05596349e-261])

In [19]:
np.arange(7)

array([0, 1, 2, 3, 4, 5, 6])

In [20]:
#And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size.
np.arange(2,8,2)

array([2, 4, 6])

In [21]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
"""Specifying your data type
While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword."""
x = np.ones(2, dtype=np.int64)

In [23]:
x

array([1, 1])

In [24]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [25]:
a = np.array([[1, 2],[ 3, 4]])
b = np.array([[5, 6],[ 7, 8]])
np.concatenate((a, b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
np.concatenate((a,b), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example.ndim

3

In [28]:
array_example.size

24

In [29]:
array_example.shape

(3, 2, 4)

In [30]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [31]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [34]:
var = "Geekforgeeks"

arr = np.fromiter(var, dtype = 'U2')

print("fromiter() array :",
      arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


In [35]:
np.arange(1, 20 , 2, 
          dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [40]:
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[4128860, 7536754, 7340144],
       [6619251, 4259932, 5570652],
       [6881380, 3801155, 7209057],
       [6029375, 7209052, 6357060]], dtype=int32)

In [43]:
import numpy as np

np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [44]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.add(a, b)
print(res)

[  7  77  23 130]


In [45]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.subtract(a, b)
print(res)

[ 3 67  3 70]


In [46]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.multiply(a, b)
print(res)

[  10  360  130 3000]


In [47]:
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.divide(a, b)
print(res)

[ 2.5        14.4         1.3         3.33333333]


In [49]:
#power
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.power(a, b)
print(res)

[                 25          1934917632        137858491849
 1152921504606846976]


In [50]:
#modulus
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
res = np.mod(a, b)
print(res)

[ 1  2  3 10]


In [66]:
#Broadcasting a Scalar to a 1D Array
arr = np.array([1, 2, 3])
res = arr + 1  
print(res)

#Broadcasting a 1D Array to a 2D Array
a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])
res = a + b
print(res)

#Broadcasting in Conditional Operations
a = np.array([12, 24, 35, 18, 60, 72])
b = np.array(["Adult", "Minor"])
res = np.where(a > 18, b[0], b[1])
print(res)

[2 3 4]
[[ 3  7 11]
 [ 9 13 17]]
['Minor' 'Adult' 'Adult' 'Minor' 'Adult' 'Adult']


In [67]:
# Adjusting Temperature Data Across Multiple Locations
temp = np.array([ [30, 32, 34, 33, 31],
                  [25, 27, 29, 28, 26],
                  [20, 22, 24, 23, 21] ])

corr = np.array([1.5, -0.5, 2.0])
res = temp + corr[:, None]
print(res)
#Normalizing Image Data
img = np.array([ [100, 120, 130],
                 [90, 110, 140],
                 [80, 100, 120] ])

m = img.mean(axis=0)
s = img.std(axis=0)
res = (img - m) / s
print(res)
#Centering Data in Machine Learning
data = np.array([ [10, 20],
                  [15, 25],
                  [20, 30] ])

m = data.mean(axis=0)
res = data - m
print(res)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]
[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]
[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]
