In [9]:
import torch as t
import pandas as pd
import numpy as  py
import matplotlib.pyplot as plt


In [10]:
print(t.__version__)

2.10.0+cpu


A tensor is a mathematical object and data structure representing an 
-dimensional array of numbers, generalizing scalars (0D), vectors (1D), and matrices (2D) 
to higher dimensions. Used extensively in physics and machine learning (e.g., TensorFlow), 
tensors organize complex data, with their rank defining the number of dimensions. 

Data Representation: Tensors hold data in 
-dimensions, making them suitable for representing complex, multi-directional physical properties (like stress or conductivity) or data in neural networks.

 

In [11]:
# scalar
scalar = t.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# get tensot back as python int
scalar.item()

7

In [14]:
# Vector - Have magnintude and direction
vector = t.tensor([7,7])
vector

tensor([7, 7])

In [15]:
vector.ndim

1

In [16]:
vector.shape

torch.Size([2])

In [18]:
# Matrix
M = t.tensor([[7,8,],
            [9,10]])
M

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
M.ndim

2

In [20]:
M.shape

torch.Size([2, 2])

In [21]:
M[1]

tensor([ 9, 10])

In [24]:
ten = t.tensor([[1,2,3],
                [3,6,9],
                [4,7,1]])
ten

tensor([[1, 2, 3],
        [3, 6, 9],
        [4, 7, 1]])

<b>Random tensors<b>

In [26]:
Rand = t.rand(3,4)
Rand

tensor([[0.7796, 0.0416, 0.0569, 0.1656],
        [0.2612, 0.0886, 0.1165, 0.9876],
        [0.1669, 0.9220, 0.3369, 0.6864]])

In [28]:
image = t.rand(size = (224,224,3))
image.shape, image.ndim

(torch.Size([224, 224, 3]), 3)

<b>Zeros and ones<b>

In [32]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0109, 0.8312, 0.0121],
        [0.7898, 0.8548, 0.5816]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [34]:

rand_tensor = torch.rand(size = (2, 3))
ones_tensor = torch.ones(size = (2, 3))
zeros_tensor = torch.zeros(size = (2, 3))

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3393, 0.5318, 0.6435],
        [0.7894, 0.8739, 0.4974]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [35]:
ones_tensor.dtype


torch.float32

<b>Creating tensors and tensors-like<b>

In [44]:
#one_ten = t.arange(1,11)
#        or
#one_ten = t.arange(start = 1, end = 11)
one_ten = t.arange(start = 0, end = 20, step = 2)
one_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [46]:
# Tensors like
tens = t.zeros_like(one_ten)
tens

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])